apiVersion: v2
name: ethereum-node
description: >
  This chart acts as an umbrella chart and allows to run a ethereum execution and
  consensus layer client. It's also able to deploy optional monitoring applications.
home: https://ethereum.org
icon: https://avatars.githubusercontent.com/u/6250754?s=200&v=4
sources:
  - https://github.com/ethpandaops/ethereum-helm-charts
type: application
version: 0.0.1

dependencies:
- name: geth
  version: "1.0.7"
  condition: geth.enabled
- name: nethermind
  version: "1.0.9"
  condition: nethermind.enabled

- name: lighthouse
  version: "1.1.1"
  condition: lighthouse.enabled
- name: teku
  version: "1.1.1"
  condition: teku.enabled
