apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "geth.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  {{- if ne .Values.volume.name "" }}
  volumeName: {{ .Values.volume.name }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.volume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}